sample_method: PNDM
beta_start: 0.0001
beta_end: 0.02
beta_schedule: linear
variance_type: learned_range
infer_num_sampling_steps: 50
guidance_scale: 1.0
dataset_dir: ./
project_dir: ''
vae_model_path: /scratch2/ml/guojun/mvgeneration/huggingface/hub/stable-diffusion-xl-base-1.0
scheduler_path: pretrained_models/scheduler
results_dir: /scratch2/ml/guojun/mvgeneration/results
annotation_name: annotation
dataset: languagetable_sim
sequence_interval: 1
val_start_frame_interval: 16
cam_ids:
- 0
accumulate_action: false
pre_encode: false
normalize: true
mode: train
anno: languagetable_original
debug: false
do_evaluate: false
final_frame_ada: false
evaluate_checkpoint: ./languagetable_original/checkpoints/0370000.pt
model: IRASim-XL/2
num_frames: 16
video_size:
- 288
- 512
learn_sigma: false
extras: 3
mask_frame_num: 1
learning_rate: 0.0001
ckpt_every: 10000
clip_max_norm: 0.1
start_clip_iter: 0
local_batch_size: 1
local_val_batch_size: 1
max_train_steps: 600000
global_seed: 3407
num_workers: 11
log_every: 100
val_every: 10000
gradient_accumulation_steps: 1
attention_mode: math
resume_from_checkpoint: /scratch2/ml/guojun/mvgeneration/results/09/21/languagetable_original/
base_dir: ''
train_annotation_path: /scratch2/ml/guojun/mvgeneration/datasets/opensource_robotdata/languagetable_sim/annotation/train
test_annotation_path: /scratch2/ml/guojun/mvgeneration/datasets/opensource_robotdata/languagetable_sim/annotation/test
val_annotation_path: /scratch2/ml/guojun/mvgeneration/datasets/opensource_robotdata/languagetable_sim/annotation/val
video_path: /scratch2/ml/guojun/mvgeneration/datasets/opensource_robotdata/languagetable_sim
fid_model_path: /scratch2/ml/guojun/mvgeneration/datasets/opensource_robotdata/evaluation_model/pt_inception-2015-12-05-6726825d.pth
fvd_model_path: /scratch2/ml/guojun/mvgeneration/datasets/opensource_robotdata/evaluation_model/i3d_torchscript.pt
fid_cache_path: /scratch2/ml/guojun/mvgeneration/datasets/opensource_robotdata/languagetable_sim/evaluation_cache/train_fid_cache.npz
true_sample_latent_videos_dir: /scratch2/ml/guojun/mvgeneration/datasets/opensource_robotdata/languagetable_sim/evaluation_latent_videos/train_sample_latent_videos
true_sample_videos_dir: /scratch2/ml/guojun/mvgeneration/datasets/opensource_robotdata/languagetable_sim/evaluation_videos/train_sample_videos
true_sample_frames_dir: /scratch2/ml/guojun/mvgeneration/datasets/opensource_robotdata/languagetable_sim/evaluation_videos/train_sample_frames
true_episode_latent_videos_dir: /scratch2/ml/guojun/mvgeneration/datasets/opensource_robotdata/languagetable_sim/latent_videos/train
true_episode_videos_dir: /scratch2/ml/guojun/mvgeneration/datasets/opensource_robotdata/languagetable_sim/videos/train
